namespace: keda
deployments:
  kedaAddOnsHttpInterceptor:
    name: keda-add-ons-http-interceptor
    containerName: keda-add-ons-http-interceptor
    image: registry.k8s.io/pause:3.10
    resources:
      requests:
        cpu: 20m
        memory: 52Mi
      limits:
        cpu: 100m
        memory: 155Mi
  kedaAddOnsHttpExternalScaler:
    name: keda-add-ons-http-external-scaler
    containerName: keda-add-ons-http-external-scaler
    image: registry.k8s.io/pause:3.10
    resources:
      requests:
        cpu: 31m
        memory: 26Mi
      limits:
        cpu: 152m
        memory: 79Mi
  kedaOperatorMetricsApiserver:
    name: keda-operator-metrics-apiserver
    containerName: keda-operator-metrics-apiserver
    image: registry.k8s.io/pause:3.10
    resources:
      requests:
        cpu: 20m
        memory: 44Mi
      limits:
        cpu: 100m
        memory: 131Mi
  kedaOperator:
    name: keda-operator
    containers:
      operator:
        name: keda-operator
        image: registry.k8s.io/pause:3.10
        resources:
          requests:
            cpu: 20m
            memory: 60Mi
          limits:
            cpu: 100m
            memory: 180Mi
      auditSidecar:
        name: audit-sidecar
        image: registry.k8s.io/pause:3.10
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            cpu: 25m
            memory: 64Mi
  kedaAdmissionWebhooks:
    name: keda-admission-webhooks
    containerName: keda-admission-webhooks
    image: registry.k8s.io/pause:3.10
    resources:
      requests:
        cpu: 20m
        memory: 23Mi
      limits:
        cpu: 100m
        memory: 70Mi
  kedifyAgent:
    name: kedify-agent
    containers:
      manager:
        name: manager
        image: registry.k8s.io/pause:3.10
        resources:
          requests:
            memory: 82Mi
            cpu: 346m
          limits:
            memory: 246Mi
            cpu: 1728m
      proxy:
        name: proxy
        image: registry.k8s.io/pause:3.10
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
